[build-system]
requires = [
    "setuptools"
]
build-backend = "setuptools.build_meta"

[project]
name = "fred-metadata"
version = "2.0.1"
authors = [
  { name="Jasmin Walter", email="Jasmin.Walter@mpi-bn.mpg.de" },
]
description = "Metadata generation, validation, search and visualization."
readme = "README.md"
dependencies = [
    "PyYAML>=5.1",
    "pytz",
    "python-dateutil",
    "tabulate",
    "seaborn",
    "biopython",
    "plotly<=6.2.0",
    "jinja2",
    "gitpython",
    "kaleido<1.0.0",
    "dash",
    "mkdocs",
    "openpyxl",
]
license = {text = "MIT"}

[project.scripts]
fred = "fred.metaTools:main"

[project.optional-dependencies]
dev = ["pytest>=7.0", "pytest-mock", "pytest-cov"]

[tool.setuptools.packages.find]
include = ["fred*"]

[tool.pytest.ini_options]
testpaths = ["test"]
python_files = ["test_*.py"]
