structure: fred # fred, mampok or path to yaml file
whitelist_repository: https://github.com/loosolab/FRED_whitelists
private_access:
  name: # github: username for access token; gitlab: oauth2 for project access token
  token: # personal (github) or project (gitlab) access token
branch: main
whitelist_path: fred
update_whitelists: True
output_path: .
filename: '_metadata' # example_metadata.yaml
email: example@email.de
